
services:
    # Hidden entity type
    hidden_entity.type:
        class: NewEntityFormBundle\FormBundle\Type\HiddenEntityType
        arguments: [@doctrine]
        tags:
            - { name: form.type, alias: hidden_entity }
